// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	pb "geekedu/common/pb"

	mock "github.com/stretchr/testify/mock"
)

// CourseServiceServer is an autogenerated mock type for the CourseServiceServer type
type CourseServiceServer struct {
	mock.Mock
}

// CreateCourse provides a mock function with given fields: _a0, _a1
func (_m *CourseServiceServer) CreateCourse(_a0 context.Context, _a1 *pb.CreateCourseRequest) (*pb.CreateCourseResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateCourse")
	}

	var r0 *pb.CreateCourseResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *pb.CreateCourseRequest) (*pb.CreateCourseResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *pb.CreateCourseRequest) *pb.CreateCourseResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.CreateCourseResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *pb.CreateCourseRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCourse provides a mock function with given fields: _a0, _a1
func (_m *CourseServiceServer) GetCourse(_a0 context.Context, _a1 *pb.GetCourseRequest) (*pb.GetCourseResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetCourse")
	}

	var r0 *pb.GetCourseResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *pb.GetCourseRequest) (*pb.GetCourseResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *pb.GetCourseRequest) *pb.GetCourseResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.GetCourseResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *pb.GetCourseRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCoverUploadURL provides a mock function with given fields: _a0, _a1
func (_m *CourseServiceServer) GetCoverUploadURL(_a0 context.Context, _a1 *pb.GetCoverUploadURLRequest) (*pb.GetCoverUploadURLResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetCoverUploadURL")
	}

	var r0 *pb.GetCoverUploadURLResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *pb.GetCoverUploadURLRequest) (*pb.GetCoverUploadURLResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *pb.GetCoverUploadURLRequest) *pb.GetCoverUploadURLResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.GetCoverUploadURLResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *pb.GetCoverUploadURLRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListCourses provides a mock function with given fields: _a0, _a1
func (_m *CourseServiceServer) ListCourses(_a0 context.Context, _a1 *pb.ListCoursesRequest) (*pb.ListCoursesResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ListCourses")
	}

	var r0 *pb.ListCoursesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *pb.ListCoursesRequest) (*pb.ListCoursesResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *pb.ListCoursesRequest) *pb.ListCoursesResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.ListCoursesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *pb.ListCoursesRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mustEmbedUnimplementedCourseServiceServer provides a mock function with no fields
func (_m *CourseServiceServer) mustEmbedUnimplementedCourseServiceServer() {
	_m.Called()
}

// NewCourseServiceServer creates a new instance of CourseServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCourseServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *CourseServiceServer {
	mock := &CourseServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
