// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	pb "geekedu/common/pb"
)

// CourseServiceClient is an autogenerated mock type for the CourseServiceClient type
type CourseServiceClient struct {
	mock.Mock
}

// CreateCourse provides a mock function with given fields: ctx, in, opts
func (_m *CourseServiceClient) CreateCourse(ctx context.Context, in *pb.CreateCourseRequest, opts ...grpc.CallOption) (*pb.CreateCourseResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateCourse")
	}

	var r0 *pb.CreateCourseResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *pb.CreateCourseRequest, ...grpc.CallOption) (*pb.CreateCourseResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *pb.CreateCourseRequest, ...grpc.CallOption) *pb.CreateCourseResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.CreateCourseResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *pb.CreateCourseRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCourse provides a mock function with given fields: ctx, in, opts
func (_m *CourseServiceClient) GetCourse(ctx context.Context, in *pb.GetCourseRequest, opts ...grpc.CallOption) (*pb.GetCourseResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetCourse")
	}

	var r0 *pb.GetCourseResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *pb.GetCourseRequest, ...grpc.CallOption) (*pb.GetCourseResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *pb.GetCourseRequest, ...grpc.CallOption) *pb.GetCourseResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.GetCourseResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *pb.GetCourseRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCoverUploadURL provides a mock function with given fields: ctx, in, opts
func (_m *CourseServiceClient) GetCoverUploadURL(ctx context.Context, in *pb.GetCoverUploadURLRequest, opts ...grpc.CallOption) (*pb.GetCoverUploadURLResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetCoverUploadURL")
	}

	var r0 *pb.GetCoverUploadURLResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *pb.GetCoverUploadURLRequest, ...grpc.CallOption) (*pb.GetCoverUploadURLResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *pb.GetCoverUploadURLRequest, ...grpc.CallOption) *pb.GetCoverUploadURLResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.GetCoverUploadURLResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *pb.GetCoverUploadURLRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListCourses provides a mock function with given fields: ctx, in, opts
func (_m *CourseServiceClient) ListCourses(ctx context.Context, in *pb.ListCoursesRequest, opts ...grpc.CallOption) (*pb.ListCoursesResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListCourses")
	}

	var r0 *pb.ListCoursesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *pb.ListCoursesRequest, ...grpc.CallOption) (*pb.ListCoursesResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *pb.ListCoursesRequest, ...grpc.CallOption) *pb.ListCoursesResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.ListCoursesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *pb.ListCoursesRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCourseServiceClient creates a new instance of CourseServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCourseServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *CourseServiceClient {
	mock := &CourseServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
