// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	pb "geekedu/common/pb"

	mock "github.com/stretchr/testify/mock"
)

// OrderServiceServer is an autogenerated mock type for the OrderServiceServer type
type OrderServiceServer struct {
	mock.Mock
}

// CheckPurchase provides a mock function with given fields: _a0, _a1
func (_m *OrderServiceServer) CheckPurchase(_a0 context.Context, _a1 *pb.CheckPurchaseRequest) (*pb.CheckPurchaseResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CheckPurchase")
	}

	var r0 *pb.CheckPurchaseResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *pb.CheckPurchaseRequest) (*pb.CheckPurchaseResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *pb.CheckPurchaseRequest) *pb.CheckPurchaseResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.CheckPurchaseResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *pb.CheckPurchaseRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateOrder provides a mock function with given fields: _a0, _a1
func (_m *OrderServiceServer) CreateOrder(_a0 context.Context, _a1 *pb.CreateOrderRequest) (*pb.CreateOrderResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 *pb.CreateOrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *pb.CreateOrderRequest) (*pb.CreateOrderResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *pb.CreateOrderRequest) *pb.CreateOrderResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.CreateOrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *pb.CreateOrderRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mustEmbedUnimplementedOrderServiceServer provides a mock function with no fields
func (_m *OrderServiceServer) mustEmbedUnimplementedOrderServiceServer() {
	_m.Called()
}

// NewOrderServiceServer creates a new instance of OrderServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderServiceServer {
	mock := &OrderServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
