// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeCourseServiceServer is an autogenerated mock type for the UnsafeCourseServiceServer type
type UnsafeCourseServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedCourseServiceServer provides a mock function with no fields
func (_m *UnsafeCourseServiceServer) mustEmbedUnimplementedCourseServiceServer() {
	_m.Called()
}

// NewUnsafeCourseServiceServer creates a new instance of UnsafeCourseServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeCourseServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeCourseServiceServer {
	mock := &UnsafeCourseServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
