// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeVideoServiceServer is an autogenerated mock type for the UnsafeVideoServiceServer type
type UnsafeVideoServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedVideoServiceServer provides a mock function with no fields
func (_m *UnsafeVideoServiceServer) mustEmbedUnimplementedVideoServiceServer() {
	_m.Called()
}

// NewUnsafeVideoServiceServer creates a new instance of UnsafeVideoServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeVideoServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeVideoServiceServer {
	mock := &UnsafeVideoServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
