// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	pb "geekedu/common/pb"

	mock "github.com/stretchr/testify/mock"
)

// VideoServiceServer is an autogenerated mock type for the VideoServiceServer type
type VideoServiceServer struct {
	mock.Mock
}

// CompleteMultipartUpload provides a mock function with given fields: _a0, _a1
func (_m *VideoServiceServer) CompleteMultipartUpload(_a0 context.Context, _a1 *pb.CompleteMultipartUploadRequest) (*pb.CompleteMultipartUploadResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CompleteMultipartUpload")
	}

	var r0 *pb.CompleteMultipartUploadResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *pb.CompleteMultipartUploadRequest) (*pb.CompleteMultipartUploadResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *pb.CompleteMultipartUploadRequest) *pb.CompleteMultipartUploadResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.CompleteMultipartUploadResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *pb.CompleteMultipartUploadRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVideoPlayURL provides a mock function with given fields: _a0, _a1
func (_m *VideoServiceServer) GetVideoPlayURL(_a0 context.Context, _a1 *pb.GetVideoPlayURLRequest) (*pb.GetVideoPlayURLResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetVideoPlayURL")
	}

	var r0 *pb.GetVideoPlayURLResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *pb.GetVideoPlayURLRequest) (*pb.GetVideoPlayURLResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *pb.GetVideoPlayURLRequest) *pb.GetVideoPlayURLResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.GetVideoPlayURLResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *pb.GetVideoPlayURLRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InitMultipartUpload provides a mock function with given fields: _a0, _a1
func (_m *VideoServiceServer) InitMultipartUpload(_a0 context.Context, _a1 *pb.InitMultipartUploadRequest) (*pb.InitMultipartUploadResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for InitMultipartUpload")
	}

	var r0 *pb.InitMultipartUploadResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *pb.InitMultipartUploadRequest) (*pb.InitMultipartUploadResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *pb.InitMultipartUploadRequest) *pb.InitMultipartUploadResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.InitMultipartUploadResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *pb.InitMultipartUploadRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mustEmbedUnimplementedVideoServiceServer provides a mock function with no fields
func (_m *VideoServiceServer) mustEmbedUnimplementedVideoServiceServer() {
	_m.Called()
}

// NewVideoServiceServer creates a new instance of VideoServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVideoServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *VideoServiceServer {
	mock := &VideoServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
