// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	pb "geekedu/common/pb"
)

// VideoServiceClient is an autogenerated mock type for the VideoServiceClient type
type VideoServiceClient struct {
	mock.Mock
}

// CompleteMultipartUpload provides a mock function with given fields: ctx, in, opts
func (_m *VideoServiceClient) CompleteMultipartUpload(ctx context.Context, in *pb.CompleteMultipartUploadRequest, opts ...grpc.CallOption) (*pb.CompleteMultipartUploadResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CompleteMultipartUpload")
	}

	var r0 *pb.CompleteMultipartUploadResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *pb.CompleteMultipartUploadRequest, ...grpc.CallOption) (*pb.CompleteMultipartUploadResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *pb.CompleteMultipartUploadRequest, ...grpc.CallOption) *pb.CompleteMultipartUploadResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.CompleteMultipartUploadResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *pb.CompleteMultipartUploadRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVideoPlayURL provides a mock function with given fields: ctx, in, opts
func (_m *VideoServiceClient) GetVideoPlayURL(ctx context.Context, in *pb.GetVideoPlayURLRequest, opts ...grpc.CallOption) (*pb.GetVideoPlayURLResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetVideoPlayURL")
	}

	var r0 *pb.GetVideoPlayURLResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *pb.GetVideoPlayURLRequest, ...grpc.CallOption) (*pb.GetVideoPlayURLResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *pb.GetVideoPlayURLRequest, ...grpc.CallOption) *pb.GetVideoPlayURLResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.GetVideoPlayURLResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *pb.GetVideoPlayURLRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InitMultipartUpload provides a mock function with given fields: ctx, in, opts
func (_m *VideoServiceClient) InitMultipartUpload(ctx context.Context, in *pb.InitMultipartUploadRequest, opts ...grpc.CallOption) (*pb.InitMultipartUploadResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for InitMultipartUpload")
	}

	var r0 *pb.InitMultipartUploadResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *pb.InitMultipartUploadRequest, ...grpc.CallOption) (*pb.InitMultipartUploadResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *pb.InitMultipartUploadRequest, ...grpc.CallOption) *pb.InitMultipartUploadResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.InitMultipartUploadResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *pb.InitMultipartUploadRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewVideoServiceClient creates a new instance of VideoServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVideoServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *VideoServiceClient {
	mock := &VideoServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
