// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/courses": {
            "get": {
                "description": "获取带分页的课程列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "课程模块"
                ],
                "summary": "获取课程列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码 (默认1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量 (默认10)",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/response.Response-handler_ListCoursesData"
                        }
                    },
                    "500": {
                        "description": "内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "教师创建一门新课程",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "课程模块"
                ],
                "summary": "创建课程",
                "parameters": [
                    {
                        "description": "课程信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.CreateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/response.Response-handler_CreateCourseData"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    },
                    "500": {
                        "description": "内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    }
                }
            }
        },
        "/api/v1/courses/cover/upload_url": {
            "get": {
                "description": "向OSS请求课程封面上传的预签名URL",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "课程模块"
                ],
                "summary": "获取封面上传链接",
                "parameters": [
                    {
                        "type": "string",
                        "description": "文件名 (如 cover.jpg)",
                        "name": "filename",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/response.Response-handler_GetCoverUploadURLData"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    },
                    "500": {
                        "description": "内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    }
                }
            }
        },
        "/api/v1/courses/{course_id}": {
            "get": {
                "description": "获取单门课程的详细信息及视频列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "课程模块"
                ],
                "summary": "获取课程详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "课程 ID",
                        "name": "course_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/response.Response-handler_GetCourseData"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    },
                    "500": {
                        "description": "内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    }
                }
            }
        },
        "/api/v1/courses/{course_id}/videos/complete": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "教师完成OSS视频分片上传后通知后端合并",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "视频模块"
                ],
                "summary": "完成视频分片上传",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "课程 ID",
                        "name": "course_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "分片合并信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.CompleteUploadRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/response.Response-handler_CompleteUploadData"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    },
                    "500": {
                        "description": "内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    }
                }
            }
        },
        "/api/v1/courses/{course_id}/videos/init": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "教师上传视频前获取OSS分片预签名URL列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "视频模块"
                ],
                "summary": "初始化视频分片上传",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "课程 ID",
                        "name": "course_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "初始化上传信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.InitUploadRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/response.Response-handler_InitUploadData"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    },
                    "500": {
                        "description": "内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    }
                }
            }
        },
        "/api/v1/orders": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "用户购买一门课程",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "订单模块"
                ],
                "summary": "创建订单",
                "parameters": [
                    {
                        "description": "购买请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.CreateOrderRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/response.Response-handler_CreateOrderData"
                        }
                    },
                    "400": {
                        "description": "参数错误或已购买",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    },
                    "500": {
                        "description": "内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    }
                }
            }
        },
        "/api/v1/videos/{video_id}/play_url": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "已购买课程的用户获取视频预签名播放链接",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "视频模块"
                ],
                "summary": "获取视频播放链接",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "视频 ID",
                        "name": "video_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/response.Response-handler_GetPlayURLData"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    },
                    "403": {
                        "description": "未购买课程",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    },
                    "500": {
                        "description": "内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "提交用户名和密码获取 JWT Token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证中心"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "登录参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登录成功",
                        "schema": {
                            "$ref": "#/definitions/response.Response-handler_LoginData"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    },
                    "401": {
                        "description": "用户名或密码错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "提交用户名和密码进行注册",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证中心"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "description": "注册参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "注册成功",
                        "schema": {
                            "$ref": "#/definitions/response.Response-handler_RegisterData"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    },
                    "409": {
                        "description": "用户名已存在",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.CompleteUploadData": {
            "type": "object",
            "properties": {
                "video_id": {
                    "type": "integer"
                }
            }
        },
        "handler.CompleteUploadRequest": {
            "type": "object",
            "required": [
                "object_key",
                "parts",
                "title",
                "upload_id"
            ],
            "properties": {
                "object_key": {
                    "type": "string"
                },
                "parts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.PartInfo"
                    }
                },
                "title": {
                    "type": "string",
                    "example": "第一节：Go语言基础"
                },
                "upload_id": {
                    "type": "string"
                }
            }
        },
        "handler.CreateCourseData": {
            "type": "object",
            "properties": {
                "course_id": {
                    "type": "integer"
                }
            }
        },
        "handler.CreateOrderData": {
            "type": "object",
            "properties": {
                "order_id": {
                    "type": "integer"
                }
            }
        },
        "handler.CreateOrderRequest": {
            "type": "object",
            "required": [
                "course_id"
            ],
            "properties": {
                "course_id": {
                    "description": "必须传课程ID",
                    "type": "integer",
                    "example": 1001
                }
            }
        },
        "handler.CreateReq": {
            "type": "object",
            "required": [
                "title"
            ],
            "properties": {
                "cover_key": {
                    "description": "前端传回 OSS 的 key",
                    "type": "string",
                    "example": "covers/xxx.jpg"
                },
                "description": {
                    "type": "string",
                    "example": "零基础入门Go语言"
                },
                "price": {
                    "type": "number",
                    "example": 99.9
                },
                "title": {
                    "type": "string",
                    "example": "Go语言实战"
                }
            }
        },
        "handler.GetCourseData": {
            "type": "object",
            "properties": {
                "course": {
                    "$ref": "#/definitions/pb.CourseItem"
                },
                "videos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pb.VideoItem"
                    }
                }
            }
        },
        "handler.GetCoverUploadURLData": {
            "type": "object",
            "properties": {
                "cover_key": {
                    "type": "string"
                },
                "upload_url": {
                    "type": "string"
                }
            }
        },
        "handler.GetPlayURLData": {
            "type": "object",
            "properties": {
                "play_url": {
                    "type": "string"
                }
            }
        },
        "handler.InitUploadData": {
            "type": "object",
            "properties": {
                "object_key": {
                    "type": "string"
                },
                "upload_id": {
                    "type": "string"
                },
                "upload_urls": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "handler.InitUploadRequest": {
            "type": "object",
            "required": [
                "filename",
                "part_count",
                "title"
            ],
            "properties": {
                "filename": {
                    "type": "string",
                    "example": "lesson1.mp4"
                },
                "part_count": {
                    "type": "integer",
                    "example": 3
                },
                "title": {
                    "type": "string",
                    "example": "第一节：Go语言基础"
                }
            }
        },
        "handler.ListCoursesData": {
            "type": "object",
            "properties": {
                "courses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pb.CourseItem"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "handler.LoginData": {
            "type": "object",
            "properties": {
                "role": {
                    "type": "integer",
                    "example": 1
                },
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                },
                "user_id": {
                    "type": "integer",
                    "example": 1001
                }
            }
        },
        "handler.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "example": "123456"
                },
                "username": {
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "handler.PartInfo": {
            "type": "object",
            "properties": {
                "etag": {
                    "type": "string",
                    "example": "\"d41d8cd98f00b204e9800998ecf8427e\""
                },
                "part_number": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "handler.RegisterData": {
            "type": "object",
            "properties": {
                "user_id": {
                    "type": "integer",
                    "example": 1001
                }
            }
        },
        "handler.RegisterRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "pb.CourseItem": {
            "type": "object",
            "properties": {
                "cover_url": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "price": {
                    "type": "number"
                },
                "teacher_id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "pb.VideoItem": {
            "type": "object",
            "properties": {
                "course_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "sort_order": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "response.Response-any": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 0
                },
                "data": {},
                "msg": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "response.Response-handler_CompleteUploadData": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 0
                },
                "data": {
                    "$ref": "#/definitions/handler.CompleteUploadData"
                },
                "msg": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "response.Response-handler_CreateCourseData": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 0
                },
                "data": {
                    "$ref": "#/definitions/handler.CreateCourseData"
                },
                "msg": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "response.Response-handler_CreateOrderData": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 0
                },
                "data": {
                    "$ref": "#/definitions/handler.CreateOrderData"
                },
                "msg": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "response.Response-handler_GetCourseData": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 0
                },
                "data": {
                    "$ref": "#/definitions/handler.GetCourseData"
                },
                "msg": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "response.Response-handler_GetCoverUploadURLData": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 0
                },
                "data": {
                    "$ref": "#/definitions/handler.GetCoverUploadURLData"
                },
                "msg": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "response.Response-handler_GetPlayURLData": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 0
                },
                "data": {
                    "$ref": "#/definitions/handler.GetPlayURLData"
                },
                "msg": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "response.Response-handler_InitUploadData": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 0
                },
                "data": {
                    "$ref": "#/definitions/handler.InitUploadData"
                },
                "msg": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "response.Response-handler_ListCoursesData": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 0
                },
                "data": {
                    "$ref": "#/definitions/handler.ListCoursesData"
                },
                "msg": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "response.Response-handler_LoginData": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 0
                },
                "data": {
                    "$ref": "#/definitions/handler.LoginData"
                },
                "msg": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "response.Response-handler_RegisterData": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 0
                },
                "data": {
                    "$ref": "#/definitions/handler.RegisterData"
                },
                "msg": {
                    "type": "string",
                    "example": "success"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "GeekEdu API 接口文档",
	Description:      "GeekEdu 微服务在线教育平台 API 网关文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
